CREATE TABLE IF NOT EXISTS "date_table" (
	"date" DATE NOT NULL UNIQUE,
	PRIMARY KEY("date")
);


CREATE INDEX "date_table_index_0"
ON "date_table" ("data");

CREATE TABLE IF NOT EXISTS "categories" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"categoria" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);


CREATE INDEX "product_type_index_0"
ON "categories" ("categoria");

CREATE TABLE IF NOT EXISTS "regions" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("id", "regiao")
);




CREATE TABLE IF NOT EXISTS "acucar_cristal_branco_cepea_esalq_sao_paulo" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "acucar_cristal_branco_cepea_esalq_sao_paulo" ("data");

CREATE TABLE IF NOT EXISTS "algodao_pluma_cepea_esalq_8_dias" (
	"date" DATE NOT NULL,
	"prazo_de_8_dias_brl" DECIMAL,
	"prazo_de_8_dias_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "algodao_pluma_cepea_esalq_8_dias" ("data");

CREATE TABLE IF NOT EXISTS "indicador_acucar_cristal_santos_fob" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_acucar_cristal_santos_fob" ("date");

CREATE TABLE IF NOT EXISTS "indicador_arroz_casca_cepea_irga_rs" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_arroz_casca_cepea_irga_rs" ("data");

CREATE TABLE IF NOT EXISTS "indicador_cafe_arabica_cepea_esalq" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_cafe_arabica_cepea_esalq" ("data");

CREATE TABLE IF NOT EXISTS "indicador_cafe_robusta_cepea_esalq" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_cafe_robusta_cepea_esalq" ("data");

CREATE TABLE IF NOT EXISTS "indicador_milho_esalq_bm_fbovespa" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_milho_esalq_bm_fbovespa" ("data");

CREATE TABLE IF NOT EXISTS "indicador_semanal_etanol_anidro_cepea_esalq_sao_paulo" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_semanal_etanol_anidro_cepea_esalq_sao_paulo" ("data");

CREATE TABLE IF NOT EXISTS "indicador_semanal_etanol_hidratado_combustivel_cepea_esalq_sao_paulo" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_semanal_etanol_hidratado_combustivel_cepea_esalq_sao_paulo" ("data");

CREATE TABLE IF NOT EXISTS "indicador_semanal_etanol_hidratado_outros_fins_cepea_esalq_sao_paulo" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_semanal_etanol_hidratado_outros_fins_cepea_esalq_sao_paulo" ("data");

CREATE TABLE IF NOT EXISTS "indicador_soja_cepea_esalq_parana" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_soja_cepea_esalq_parana" ("data");

CREATE TABLE IF NOT EXISTS "indicador_soja_cepea_esalq_paranagua" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "indicador_soja_cepea_esalq_paranagua" ("data");

CREATE TABLE IF NOT EXISTS "preco_medio_trigo_cepea_esalq_parana" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "preco_medio_trigo_cepea_esalq_parana" ("data");

CREATE TABLE IF NOT EXISTS "preco_medio_trigo_cepea_esalq_rio_grande_sul" (
	"date" DATE NOT NULL,
	"a_vista_brl" DECIMAL,
	"a_vista_usd" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "preco_medio_trigo_cepea_esalq_rio_grande_sul" ("data");

CREATE TABLE IF NOT EXISTS "precos_farinha_mandioca_seca_fina_branca_crua_tipo_1" (
	"date" DATE NOT NULL,
	"som_a_vista_brl" DECIMAL,
	"som_a_prazo" DECIMAL,
	"som_prazo_pgto" DECIMAL,
	"cop_a_vista_brl" DECIMAL,
	"cop_a_prazo" DECIMAL,
	"cop_prazo_pgto" DECIMAL,
	"eop_a_vista_brl" DECIMAL,
	"eop_a_prazo" DECIMAL,
	"eop_prazo_pgto" DECIMAL,
	"nop_a_vista_brl" DECIMAL,
	"nop_a_prazo" DECIMAL,
	"nop_prazo_pgto" DECIMAL,
	"aic_a_vista_brl" DECIMAL,
	"aic_a_prazo" DECIMAL,
	"aic_prazo_pgto" DECIMAL,
	"lsc_a_vista_brl" DECIMAL,
	"lsc_a_prazo" DECIMAL,
	"lsc_prazo_pgto" DECIMAL,
	"ass_a_vista_brl" DECIMAL,
	"ass_a_prazo" DECIMAL,
	"ass_prazo_pgto" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "precos_farinha_mandioca_seca_fina_branca_crua_tipo_1" ("data");

CREATE TABLE IF NOT EXISTS "precos_farinha_mandioca_seca_grossa_branca_crua_tipo_1" (
	"date" DATE NOT NULL,
	"som_a_vista_brl" DECIMAL,
	"som_a_prazo" DECIMAL,
	"som_prazo_pgto" DECIMAL,
	"cop_a_vista_brl" DECIMAL,
	"cop_a_prazo" DECIMAL,
	"cop_prazo_pgto" DECIMAL,
	"eop_a_vista_brl" DECIMAL,
	"eop_a_prazo" DECIMAL,
	"eop_prazo_pgto" DECIMAL,
	"nop_a_vista_brl" DECIMAL,
	"nop_a_prazo" DECIMAL,
	"nop_prazo_pgto" DECIMAL,
	"lsc_a_vista_brl" DECIMAL,
	"lsc_a_prazo" DECIMAL,
	"lsc_prazo_pgto" DECIMAL,
	"ass_a_vista_brl" DECIMAL,
	"ass_a_prazo" DECIMAL,
	"ass_prazo_pgto" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "precos_farinha_mandioca_seca_grossa_branca_crua_tipo_1" ("data");

CREATE TABLE IF NOT EXISTS "precos_fecula_mandioca" (
	"date" DATE NOT NULL,
	"esm_a_vista_brl" DECIMAL,
	"esm_a_prazo" DECIMAL,
	"esm_prazo_pgto" DECIMAL,
	"som_a_vista_brl" DECIMAL,
	"som_a_prazo" DECIMAL,
	"som_prazo_pgto" DECIMAL,
	"cop_a_vista_brl" DECIMAL,
	"cop_a_prazo" DECIMAL,
	"cop_prazo_pgto" DECIMAL,
	"eop_a_vista_brl" DECIMAL,
	"eop_a_prazo" DECIMAL,
	"eop_prazo_pgto" DECIMAL,
	"nop_a_vista_brl" DECIMAL,
	"nop_a_prazo" DECIMAL,
	"nop_prazo_pgto" DECIMAL,
	"sop_a_vista_brl" DECIMAL,
	"sop_a_prazo" DECIMAL,
	"sop_prazo_pgto" DECIMAL,
	"aic_a_vista_brl" DECIMAL,
	"aic_a_prazo" DECIMAL,
	"aic_prazo_pgto" DECIMAL,
	"lsc_a_vista_brl" DECIMAL,
	"lsc_a_prazo" DECIMAL,
	"lsc_prazo_pgto" DECIMAL,
	"ass_a_vista_brl" DECIMAL,
	"ass_a_prazo" DECIMAL,
	"ass_prazo_pgto" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "precos_fecula_mandioca" ("data");

CREATE TABLE IF NOT EXISTS "precos_feijao_carioca_notas_8_85_cepea_cna" (
	"date" DATE NOT NULL,
	"barreiras_valor_brl/sc" DECIMAL,
	"belo_horizonte_valor_brl/sc" DECIMAL,
	"centro_noroeste_goiano_valor_brl/sc" DECIMAL,
	"curitiba_valor_brl/sc" DECIMAL,
	"distrito_federal_valor_brl/sc" DECIMAL,
	"itapeva_valor_brl/sc" DECIMAL,
	"leste_de_sc_valor_brl/sc" DECIMAL,
	"leste_goiano_valor_brl/sc" DECIMAL,
	"metade_sul_do_parana_valor_brl/sc" DECIMAL,
	"nordeste_rio-grandense_valor_brl/sc" DECIMAL,
	"noroeste_de_minas_valor_brl/sc" DECIMAL,
	"noroeste_do_parana_valor_brl/sc" DECIMAL,
	"norte_goiano_valor_brl/sc" DECIMAL,
	"oeste_catarinense_valor_brl/sc" DECIMAL,
	"sao_paulo_valor_brl/sc" DECIMAL,
	"sorriso_valor_brl/sc" DECIMAL,
	"sul_goiano_valor_brl/sc" DECIMAL,
	"sul/sudoeste_de_minas_valor_brl/sc" DECIMAL,
	"triangmineiro/alto_paranaiba_valor_brl/sc" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "precos_feijao_carioca_notas_8_85_cepea_cna" ("data");

CREATE TABLE IF NOT EXISTS "precos_feijao_preto_tipo_1_cepea_cna" (
	"date" DATE NOT NULL,
	"centro_rio-grandense_valor_brl/sc" DECIMAL,
	"curitiba_valor_brl/sc" DECIMAL,
	"itapeva_valor_brl/sc" DECIMAL,
	"leste_de_sc_valor_brl/sc" DECIMAL,
	"metade_sul_do_parana_valor_brl/sc" DECIMAL,
	"nordeste_rio-grandense_valor_brl/sc" DECIMAL,
	"noroeste_do_parana_valor_brl/sc" DECIMAL,
	"noroeste_do_rio_grande_do_sul_valor_brl/sc" DECIMAL,
	"oeste_catarinense_valor_brl/sc" DECIMAL,
	"sao_paulo_valor_brl/sc" DECIMAL,
	"sorriso_valor_brl/sc" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "precos_feijao_preto_tipo_1_cepea_cna" ("data");

CREATE TABLE IF NOT EXISTS "precos_raiz_mandioca" (
	"date" DATE NOT NULL,
	"esm_a_vista_brl" DECIMAL,
	"esm_a_prazo" DECIMAL,
	"esm_prazo_pgto" DECIMAL,
	"som_a_vista_brl" DECIMAL,
	"som_a_prazo" DECIMAL,
	"som_prazo_pgto" DECIMAL,
	"cop_a_vista_brl" DECIMAL,
	"cop_a_prazo" DECIMAL,
	"cop_prazo_pgto" DECIMAL,
	"eop_a_vista_brl" DECIMAL,
	"eop_a_prazo" DECIMAL,
	"eop_prazo_pgto" DECIMAL,
	"nop_a_vista_brl" DECIMAL,
	"nop_a_prazo" DECIMAL,
	"nop_prazo_pgto" DECIMAL,
	"sop_a_vista_brl" DECIMAL,
	"sop_a_prazo" DECIMAL,
	"sop_prazo_pgto" DECIMAL,
	"aic_a_vista_brl" DECIMAL,
	"aic_a_prazo" DECIMAL,
	"aic_prazo_pgto" DECIMAL,
	"lsc_a_vista_brl" DECIMAL,
	"lsc_a_prazo" DECIMAL,
	"lsc_prazo_pgto" DECIMAL,
	"ass_a_vista_brl" DECIMAL,
	"ass_a_prazo" DECIMAL,
	"ass_prazo_pgto" DECIMAL,
	"tipo_de_produto" TEXT NOT NULL,
	"regiao" TEXT NOT NULL,
	PRIMARY KEY("date", "tipo_de_produto", "regiao")
);


CREATE INDEX "acucar_cristal_branco_cepea_esalq_sao_paulo.csv_index_0"
ON "precos_raiz_mandioca" ("data");
ALTER TABLE "precos_farinha_mandioca_seca_fina_branca_crua_tipo_1"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_fecula_mandioca"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "preco_medio_trigo_cepea_esalq_parana"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_cafe_arabica_cepea_esalq"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_cafe_robusta_cepea_esalq"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_semanal_etanol_anidro_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_milho_esalq_bm_fbovespa"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_semanal_etanol_hidratado_outros_fins_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_soja_cepea_esalq_parana"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_raiz_mandioca"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "preco_medio_trigo_cepea_esalq_rio_grande_sul"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "acucar_cristal_branco_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_feijao_preto_tipo_1_cepea_cna"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_farinha_mandioca_seca_grossa_branca_crua_tipo_1"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "algodao_pluma_cepea_esalq_8_dias"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_acucar_cristal_santos_fob"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_arroz_casca_cepea_irga_rs"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_feijao_carioca_notas_8_85_cepea_cna"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_semanal_etanol_hidratado_combustivel_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_soja_cepea_esalq_paranagua"
ADD FOREIGN KEY("date") REFERENCES "date_table"("date")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_soja_cepea_esalq_parana"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_semanal_etanol_hidratado_outros_fins_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_milho_esalq_bm_fbovespa"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_semanal_etanol_anidro_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_cafe_robusta_cepea_esalq"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_cafe_arabica_cepea_esalq"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "preco_medio_trigo_cepea_esalq_parana"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_farinha_mandioca_seca_fina_branca_crua_tipo_1"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_fecula_mandioca"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_soja_cepea_esalq_paranagua"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_arroz_casca_cepea_irga_rs"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_feijao_carioca_notas_8_85_cepea_cna"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_semanal_etanol_hidratado_combustivel_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_acucar_cristal_santos_fob"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "algodao_pluma_cepea_esalq_8_dias"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_farinha_mandioca_seca_grossa_branca_crua_tipo_1"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_feijao_preto_tipo_1_cepea_cna"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "acucar_cristal_branco_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "preco_medio_trigo_cepea_esalq_rio_grande_sul"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_raiz_mandioca"
ADD FOREIGN KEY("tipo_de_produto") REFERENCES "categories"("categoria")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_fecula_mandioca"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "regions"
ADD FOREIGN KEY("regiao") REFERENCES "indicador_soja_cepea_esalq_paranagua"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_arroz_casca_cepea_irga_rs"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_feijao_carioca_notas_8_85_cepea_cna"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_semanal_etanol_hidratado_combustivel_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_acucar_cristal_santos_fob"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "algodao_pluma_cepea_esalq_8_dias"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_farinha_mandioca_seca_grossa_branca_crua_tipo_1"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_feijao_preto_tipo_1_cepea_cna"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_farinha_mandioca_seca_fina_branca_crua_tipo_1"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "preco_medio_trigo_cepea_esalq_parana"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "acucar_cristal_branco_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_cafe_arabica_cepea_esalq"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_cafe_robusta_cepea_esalq"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "preco_medio_trigo_cepea_esalq_rio_grande_sul"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_semanal_etanol_anidro_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "precos_raiz_mandioca"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_milho_esalq_bm_fbovespa"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_semanal_etanol_hidratado_outros_fins_cepea_esalq_sao_paulo"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "indicador_soja_cepea_esalq_parana"
ADD FOREIGN KEY("regiao") REFERENCES "regions"("regiao")
ON UPDATE CASCADE ON DELETE CASCADE;